---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:
      
  - name: Variable ausgeben
    debug:
      msg: "{{ item }}"
    loop:
       - apple
       - banana
       - pear
