---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
      msg: "Hello Server! nochmal" 
  
  - name: neue Datei anlegen
  file:
    path: /tmp/neue_datei
    state: touch
